language: java
script: mvn package
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis/deploy.sh"
  on:
    branch: master
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - secure: s0jXNZvzTxFFDkcie6vHHVeLaQYsez50uxiMh/UDsedkbSzoFlXU+uoxoPEfmfiZaUdDtEZnkOF251OJvsQzq+9o6FEfEs42SsomQkPyMH/aHtV4pOfWJRwtGiJGMW5W5zGGJkX037uksXkfwQ/dpKzZ4j5RkbZ29kWJEin3avMxZTNwgNOc+ix49YdG/QVHo9IzOo3zImfXTF0F582cJPlSrrXCRQo+d1iroOPV6Azh2Bgf8Ps/DICEhbfyz4FFlxW2uLcOBwBDmvpZR1jSUfX4w7t/g9jUwvJ0ftRQGtk9lUBpZJ+ILCTDs6mI/kJQa2fDFxE2+lH/To9RHIylwiQdkLthMWepD47ElAWiUFDUxVatFcKX3wEMsAVEUmzOUHvtZFWsGiJVdCAF4hxLfyEvmaMuNTrxC8tgt1xi5UPA939n8iU0p/BalPi6PlwofhaK9swpVL7r2eoNzGz5yV2kjioCqdc+OaRKsZeugqVmyFa6bh4BKN0+lLtLwU+nbEQxZJJ9ebXjAcdGmYCSiSSldoDGMoQjsXAZtt1egUzzJOXqEz0OIzqvqbMLezBlBH1TgkU2QE2rOIgD/UH9DmbV0nh2YsZqJJ36HmH524E/1s3q+H0RqQIerOzZfJuWMw/0teEJzWl1s5CgalTZ19pTC8EAIGWW1TqLknZ/NZU=
  - GPG_KEY_NAME=navikt
  - secure: tFgILtVmq7o/F+UJ7rUmnbqtXoaA259LorHvyUjL0G4e86/a1s1kxWOJa6OG5WUuFJSekW/EjVVuvRNMRfE4lnh7TepwowE1t8orcHdB/oYVgAUdGi7GiwngHZmUpaONvO8JAUDYqYJoE8963E4Mhwe0tLc1wwYgg0IKh4qC9ECuQqdtowhj497TBPXiKh4gLrKvKjF+Nv7EAIzg3I1pg7kj1JpV3r9XOAbTUrTx0h1TXNLsId1lWbWVqsbwLKGJHnllEual13qbCNpk6YCg3qbluOP1HdD0o+jhc13V2mdwtFSNwiVSsYtIyPxVfvdrxJSrRabfX33r7W60cPLXEhumSbYjpTkat6wyUiQkmZwJd9svuq7J5nXZayBrbuIP+U6uZCaAJwxv8C8mWeGutBHZt2CsD0NfHoBZeJLeCeYtGJVpsJ8csY9x5YpXyDs5UwWkZl00Brway61gm1v80xKIFhE42YiVztEfNEWu03fsTD9rqFSrrf56duJ0HHuOZ4y30Vj/vyFQ6vvHhanaOL069sjot828Jp959OCe1FRFFzarsMDSAtf0lP631rrZL+ekXrya/0P0iUef0ZZJzmU3DOhWUFyu2aopu8n7eUTs3EP998j4Txsc6wrMDKXbx1HfumKRh+XeetMyHaKGPvuAwiXU+rEu7xtLfnhsH7A=
