version: 2.1

jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk
        steps:
            - checkout
            - restore_cache:
                  name: Restore cached dependencies
                  keys:
                      - maven3-{{ checksum "pom.xml" }}
            - run:
                  name: Resolve/Update Dependencies
                  command: mvn dependency:resolve-plugins dependency:go-offline
            - save_cache:
                  name: Cache Maven dependencies
                  key: maven3-{{ checksum "pom.xml" }}
                  paths:
                      - ~/.m2
            - run:
                  name: Build (and run tests)
                  command: "mvn clean install"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
