version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - maven3-{{ checksum "pom.xml" }}
      - run:
          name: Build (and run tests)
          command: mvn clean install
      - save_cache:
          name: Cache Maven dependencies
          key: maven3-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - maven3-{{ checksum "pom.xml" }}
      - run:
          name: Import gpg key
          command: echo $GPG_KEY_BASE64 | base64 --decode | gpg --yes --batch --import
      - run:
          name: DEbug
          command: .circleci/debug.sh
      - run:
          name: Deploy to Maven Central
          command: "mvn --settings .circleci/settings.xml deploy -Prelease,deploy-to-sonatype -DskipTests=true -X -e"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - deploy:
          context: Maven Central Release
          #requires:
           # - build
          filters:
            branches:
              only: circle-ci
